---
- job:
    name: demo-job
    run: playbooks/demojob.yaml

- project:
    default-branch: main
    check:
      jobs:
        - demo-job
    gate:
      jobs:
        - demo-job
    post:
      jobs:
        - demo-job
    tag:
      jobs:
        - demo-job
